input:
  parameters:
    cycle: t00z
    PDY: 20240224

  datasets:
    - name: atms
      data_kind: observation   # increment | analysis | forecast | restart | observation | etc.
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_obs/fv3/20240224 
        filename: obs.20240224.t00z.atms_n20.nc
        group: ObsValue
        var_list:
          - brightnessTemperature
        channels: [2, 7, 15, 22]
      colormap:
        default: gist_ncar_r
        brightnessTemperature: null
      range:
        default:
          vmin: null
          vmax: null
        brightnessTemperature:
          vmin: null
          vmax: null
      title: "ATMS_N20"

    - name: ghcn
      data_kind: observation   # increment | analysis | forecast | restart | observation | etc.
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_obs/ghcn
        filename: obs.20250121.t00z.ghcn_snow.nc
        group: ObsValue
        var_list:
          - totalSnowDepth
        channels: null
      colormap:
        default: gist_ncar_r
        totalSnowDepth: null
      range:
        default:
          vmin: null
          vmax: null
        totalSnowDepth:
          vmin: null
          vmax: null
      title: "GHCN snow"

output:
  path: ./
  prefix: obs

plot:
  cartopy_ne_path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/NaturalEarth
  projection:
    name: Robinson    # Robinson | PlateCarree | Mollweide 
    central_longitude: -77.0369  # D.C.
  figure:
    figsize: [5, 2.5]
    dpi: 300
  colorbar:
    extend: both   # neither | both | min | max
    size: "3.5%"
    pad: 0.08
    label_fontsize: 8
    tick_fontsize: 7
  title:
    fontsize: 9
  scatter:
    marker_size: 0.5
  background:
    features:
      - coastline
      #- land
      #- lakes
      #- states
      #- borders
    resolution: 50m
    linewidth: 0.5
    alpha: 0.7

