input:
  parameters:
    cycle: t00z
    PDY: 20250121

  datasets:
    - name: before
      data_kind: analysis   # increment | analysis | forecast | restart | observation | etc.
      geo:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_fix/FV3/Tiled/C96
        filename: C96.mx100_oro_data
        file_type: orog      # file | orog
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_ref/land
        filename: 20250121.000000.sfc_data.before
        file_type: tile      # file | tile
        var_list:
          - snwdph
          - smc
        z_index: 0
        time_index: 0
      colormap:
        default: gist_ncar_r
        snwdph: null
        smc: null
      range:
        default:
          vmin: null
          vmax: null
        snwdph:
          vmin: null
          vmax: null
        smc:
          vmin: null
          vmax: null
      title: "snow-DA: before analysis"

    - name: after
      data_kind: analysis   # increment | analysis | forecast | restart | observation | etc.
      geo:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_fix/FV3/Tiled/C96
        filename: C96.mx100_oro_data
        file_type: orog      # file | orog
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_ref/land
        filename: 20250121.000000.sfc_data.after
        file_type: tile      # file | tile
        var_list:
          - snwdph
          - smc
        z_index: 0
        time_index: 0
      colormap:
        default: gist_ncar_r
        snwdph: null
        smc: null
      range:
        default:
          vmin: null
          vmax: null
        snwdph:
          vmin: null
          vmax: null
        smc:
          vmin: null
          vmax: null
      title: "snow-DA: after analysis"

  differences:
    - name: A-B
      base: after
      minus: before
      var_map:
        snwdph: snwdph
        smc: smc
      colormap:
        default: RdBu_r
        snwdph: RdBu_r
        smc: RdBu_r
      range:
        default:
          vmin: null
          vmax: null
        snwdph:
          vmin: null
          vmax: null
        smc:
          vmin: null
          vmax: null
      title: "snow-DA: after-before"

output:
  path: ./
  prefix: snowAnal

plot:
  cartopy_ne_path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/NaturalEarth
  projection:
    name: Robinson    # Robinson | PlateCarree | Mollweide 
    central_longitude: -77.0369  # D.C.
  figure:
    figsize: [5, 2.5]
    dpi: 300
  colorbar:
    extend: both   # neither | both | min | max
    size: "3.5%"
    pad: 0.08
    label_fontsize: 8
    tick_fontsize: 7
  title:
    fontsize: 9
  background:
    features:
      - coastline
      #- land
      #- lakes
      #- states
      #- borders
    resolution: 50m
    linewidth: 0.5
    alpha: 0.7

