input:
  parameters:
    cycle: t00z
    PDY: 20250121

  datasets:
    - name: sfc_data
      data_kind: restart   # increment | analysis | forecast | restart | observation etc.
      geo:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_fix/FV3/Tiled/C96
        filename: C96.mx100_oro_data
        file_type: orog      # file | orog | tile
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_ref/restart
        filename: '*.sfc_data.tile1.nc'
        file_type: tile      # file | tile
        var_list:
          - snwdph
        z_index: 0
        time_index: 0
      colormap:
        default: gist_ncar_r
        snwdph: null
      range:
        default:
          vmin: null
          vmax: null
        snwdph:
          vmin: null
          vmax: null
      title: "restart sfc_data"

output:
  path: ./
  prefix: rst

plot:
  cartopy_ne_path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/NaturalEarth
  projection:
    name: Robinson    # Robinson | PlateCarree | Mollweide 
    central_longitude: -77.0369  # D.C.
  figure:
    figsize: [5, 2.5]
    dpi: 300
  colorbar:
    extend: both   # neither | both | min | max
    size: "3.5%"
    pad: 0.08
    label_fontsize: 8
    tick_fontsize: 7
  title:
    fontsize: 9
  background:
    features:
      - coastline
      #- land
      #- lakes
      #- states
      #- borders
    resolution: 50m
    linewidth: 0.5
    alpha: 0.7

