input:
  parameters:
    cycle: t00z
    PDY: 20250121

  datasets:
    - name: sfc
      data_kind: forecast   # increment | analysis | forecast | restart | observation etc.
      geo:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_ref/forecast
        filename: ufsda.t00z.sfc.f*.c96.tile1.nc
        file_type: tile      # file | orog | tile
      data:
        path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/DATA_ref/forecast
        filename: ufsda.t00z.sfc.f*.c96.tile1.nc
        file_type: tile      # file | tile
        var_list:
          - snod
        z_index: 0
        time_index: 0
      colormap:
        default: gist_ncar_r
        snod: null
      range:
        default:
          vmin: null
          vmax: null
        snod:
          vmin: null
          vmax: null
      title: "forecast sfc"

output:
  path: ./
  prefix: fcst

plot:
  cartopy_ne_path: /work2/noaa/epic/UFS-DA-Workflow_v1.0/inputs/NaturalEarth
  projection:
    name: Robinson    # Robinson | PlateCarree | Mollweide 
    central_longitude: -77.0369  # D.C.
  figure:
    figsize: [5, 2.5]
    dpi: 300
  colorbar:
    extend: both   # neither | both | min | max
    size: "3.5%"
    pad: 0.08
    label_fontsize: 8
    tick_fontsize: 7
  title:
    fontsize: 9
  background:
    features:
      - coastline
      #- land
      #- lakes
      #- states
      #- borders
    resolution: 50m
    linewidth: 0.5
    alpha: 0.7

