name: test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - xarray
  - netcdf4
  - cartopy
  - matplotlib
  - pytest
  - PyYAML
  - pip
  - sphinx
  - sphinx-rtd-theme
  - myst-parser
  - sphinxcontrib-mermaid
