name: ci_pytest

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env/ci_environment.yml
          activate-environment: test
          use-mamba: true
          auto-activate-base: false

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: |
          conda run -n test pytest -x -ra

